// <auto-generated />
using System;
using Flowboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowboard.Api.Migrations
{
    [DbContext(typeof(FlowboardDbContext))]
    [Migration("20260828034037_AddCardActivity")]
    partial class AddCardActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CardId", "CreatedDate")
                        .HasDatabaseName("IX_ActivityEvent_CardId_CreatedDate");

                    b.ToTable("ActivityEvent", (string)null);
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("#64748b");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Starred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Board", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#64748b",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Fixture Board",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Starred = false,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#4f46e5",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Product Roadmap Q3",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Starred = true,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#7c3aed",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Marketing Launch",
                            PublicId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Starred = false,
                            WorkspaceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = "#16a34a",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Customer Support",
                            PublicId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Starred = false,
                            WorkspaceId = 1
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.BoardMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BoardId", "UserId")
                        .IsUnique();

                    b.ToTable("BoardMember", null, t =>
                        {
                            t.HasCheckConstraint("CK_BoardMember_Role", "[Role] IN ('BoardAdmin','BoardMember','Observer')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "BoardMember",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "BoardMember",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "BoardMember",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "BoardMember",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "BoardMember",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DueComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<double>("Position")
                        .HasColumnType("float");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("ListId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ListId", "Position");

                    b.ToTable("Card", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 1,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000012"),
                            RowVersion = new byte[0],
                            Title = "Define SSO requirements for Enterprise"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 1,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000013"),
                            RowVersion = new byte[0],
                            Title = "Accessibility audit (WCAG 2.2 AA)"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 1,
                            Position = 3000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000014"),
                            RowVersion = new byte[0],
                            Title = "Prototype smoke card"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 2,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000015"),
                            RowVersion = new byte[0],
                            Title = "Card detail redesign"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 2,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000016"),
                            RowVersion = new byte[0],
                            Title = "Empty-state illustrations"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 3,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000017"),
                            RowVersion = new byte[0],
                            Title = "Drag & drop performance on large boards"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 3,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000018"),
                            RowVersion = new byte[0],
                            Title = "Research competitor onboarding flows"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 3,
                            Position = 3000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000019"),
                            RowVersion = new byte[0],
                            Title = "Board member invitations"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 3,
                            Position = 4000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000001a"),
                            RowVersion = new byte[0],
                            Title = "Label filter in the top bar"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 4,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000001b"),
                            RowVersion = new byte[0],
                            Title = "Keyboard shortcuts pass"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 4,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000001c"),
                            RowVersion = new byte[0],
                            Title = "Activity feed pagination"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 5,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000001d"),
                            RowVersion = new byte[0],
                            Title = "Launch messaging brief"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 5,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000001e"),
                            RowVersion = new byte[0],
                            Title = "Press kit assets"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 5,
                            Position = 3000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000001f"),
                            RowVersion = new byte[0],
                            Title = "Social calendar"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 5,
                            Position = 4000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000020"),
                            RowVersion = new byte[0],
                            Title = "Partner co-marketing outreach"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 6,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000021"),
                            RowVersion = new byte[0],
                            Title = "Update FAQ for v2 pricing"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueComplete = false,
                            IsDeleted = false,
                            ListId = 6,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000022"),
                            RowVersion = new byte[0],
                            Title = "Escalation runbook review"
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.CardLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LabelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("CardId", "LabelId")
                        .IsUnique();

                    b.ToTable("CardLabel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 1
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 2
                        },
                        new
                        {
                            Id = 3,
                            CardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 3
                        },
                        new
                        {
                            Id = 4,
                            CardId = 4,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 2
                        },
                        new
                        {
                            Id = 5,
                            CardId = 5,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 2
                        },
                        new
                        {
                            Id = 6,
                            CardId = 6,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 4
                        },
                        new
                        {
                            Id = 7,
                            CardId = 6,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 5
                        },
                        new
                        {
                            Id = 8,
                            CardId = 7,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 3
                        },
                        new
                        {
                            Id = 9,
                            CardId = 7,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 4
                        },
                        new
                        {
                            Id = 10,
                            CardId = 8,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 1
                        },
                        new
                        {
                            Id = 11,
                            CardId = 9,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 1
                        },
                        new
                        {
                            Id = 12,
                            CardId = 10,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 1
                        },
                        new
                        {
                            Id = 13,
                            CardId = 11,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LabelId = 4
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.CardMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CardId", "UserId")
                        .IsUnique();

                    b.ToTable("CardMember", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CardId = 4,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            CardId = 5,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CardId = 6,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CardId = 7,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CardId = 8,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CardId = 8,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CardId = 9,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            CardId = 10,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            CardId = 11,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Done")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("Position")
                        .HasColumnType("float");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("ChecklistItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 4,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Done = true,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000030"),
                            Text = "Wireframes"
                        },
                        new
                        {
                            Id = 2,
                            CardId = 4,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Done = true,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000031"),
                            Text = "Visual design"
                        },
                        new
                        {
                            Id = 3,
                            CardId = 4,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Done = false,
                            Position = 3000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000032"),
                            Text = "Prototype interactions"
                        },
                        new
                        {
                            Id = 4,
                            CardId = 6,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Done = true,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000033"),
                            Text = "Profile virtualized rendering"
                        },
                        new
                        {
                            Id = 5,
                            CardId = 6,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Done = false,
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000034"),
                            Text = "Test with 500+ card board"
                        },
                        new
                        {
                            Id = 6,
                            CardId = 7,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Done = false,
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000035"),
                            Text = "Document top 3 competitor flows"
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CardId");

                    b.ToTable("Comment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Body = "Repro steps attached in the linked doc.",
                            CardId = 6,
                            CreatedBy = "00000000-0000-0000-0000-000000000006",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Body = "Started a competitor matrix, will share by EOW.",
                            CardId = 7,
                            CreatedBy = "00000000-0000-0000-0000-000000000005",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("BoardId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Invitation_BoardId_Email_Pending")
                        .HasFilter("[Status] = 'Pending'");

                    b.ToTable("Invitation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invitation_Role", "[Role] IN ('BoardAdmin','BoardMember','Observer')");

                            t.HasCheckConstraint("CK_Invitation_Status", "[Status] IN ('Pending','Accepted','Revoked')");
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Label", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 2,
                            Color = "#16a34a",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Feature",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000023")
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 2,
                            Color = "#7c3aed",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Design",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000024")
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 2,
                            Color = "#2563eb",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Research",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000025")
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 2,
                            Color = "#dc2626",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bug",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000026")
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 2,
                            Color = "#991b1b",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Urgent",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000027")
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Position")
                        .HasColumnType("float");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WipLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("BoardId", "Position");

                    b.ToTable("List", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Backlog",
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Design",
                            Position = 2000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000000d"),
                            WipLimit = 3
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "In Progress",
                            Position = 3000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000000e"),
                            WipLimit = 3
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 2,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Review",
                            Position = 4000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-00000000000f"),
                            WipLimit = 2
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 3,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "To Do",
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = 6,
                            BoardId = 4,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Open Tickets",
                            Position = 1000.0,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000011")
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarColor = "#64748b",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Fixture Owner",
                            Email = "fixture-owner@flowboard.test",
                            Initials = "FO",
                            PasswordHash = "$2a$12$DISABLED.NO.CREDENTIAL.SHIPPED.IN.THIS.MIGRATION.SEED",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            AvatarColor = "#2563eb",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Aiko Kimura",
                            Email = "fixture-member-ak@flowboard.test",
                            Initials = "AK",
                            PasswordHash = "$2a$12$DISABLED.NO.CREDENTIAL.SHIPPED.IN.THIS.MIGRATION.SEED",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 3,
                            AvatarColor = "#7c3aed",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Luca Ferrari",
                            Email = "fixture-member-lf@flowboard.test",
                            Initials = "LF",
                            PasswordHash = "$2a$12$DISABLED.NO.CREDENTIAL.SHIPPED.IN.THIS.MIGRATION.SEED",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = 4,
                            AvatarColor = "#16a34a",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Omar Haddad",
                            Email = "fixture-member-oh@flowboard.test",
                            Initials = "OH",
                            PasswordHash = "$2a$12$DISABLED.NO.CREDENTIAL.SHIPPED.IN.THIS.MIGRATION.SEED",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = 5,
                            AvatarColor = "#ea580c",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Priya Nair",
                            Email = "fixture-member-pn@flowboard.test",
                            Initials = "PN",
                            PasswordHash = "$2a$12$DISABLED.NO.CREDENTIAL.SHIPPED.IN.THIS.MIGRATION.SEED",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = 6,
                            AvatarColor = "#b91c1c",
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Tomás Bravo",
                            Email = "fixture-member-tb@flowboard.test",
                            Initials = "TB",
                            PasswordHash = "$2a$12$DISABLED.NO.CREDENTIAL.SHIPPED.IN.THIS.MIGRATION.SEED",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Workspace", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "MIGRATION",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Fixture Workspace",
                            OwnerUserId = 1,
                            PublicId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.ActivityEvent", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowboard.Api.Domain.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Board", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.BoardMember", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowboard.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Card", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.CardLabel", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Card", "Card")
                        .WithMany("CardLabels")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowboard.Api.Domain.Entities.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.CardMember", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Card", "Card")
                        .WithMany("CardMembers")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowboard.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Card", "Card")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowboard.Api.Domain.Entities.Card", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowboard.Api.Domain.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Label", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.List", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("Flowboard.Api.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Flowboard.Api.Domain.Entities.Card", b =>
                {
                    b.Navigation("CardLabels");

                    b.Navigation("CardMembers");

                    b.Navigation("ChecklistItems");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
